variables:
  GITHUB_TARGET_REPOSITORY: portfolio-3d

stages:
  - deploy

deploy:
  stage: deploy
  only:
    - branches
  script:
    - git config --global user.email "gitlab-ci@example.com"
    - git config --global user.name "GitLab CI/CD"
    - git remote set-url --push origin
      https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_TARGET_REPOSITORY}.git
    - git push --all --tags --force
