stages:
  - deploy

deploy:
  stage: deploy
  only:
    - branches
  script:
    - git config --global user.email "lampd.work@gmail.com"
    - git config --global user.name "lampd"
    - git remote set-url --push origin
      https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_USERNAME}/${GITHUB_TARGET_REPOSITORY}.git
    - git checkout main
    - git push -f origin main
    - git checkout develop
    - git push -f origin develop
