stages:
  - deploy

deploy:
  stage: mirror
  script:
    - git remote add mirror
      https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_TARGET_USERNAME}/${GITHUB_TARGET_REPOSITORY}.git
    - git push --mirror mirror
